# Generated by Django 4.1.7 on 2023-05-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RANKING', models.IntegerField()),
                ('CAUSE', models.CharField(max_length=255)),
                ('COUNT', models.IntegerField()),
                ('DEATH_COUNT', models.IntegerField()),
                ('INJURED_COUNT', models.IntegerField()),
                ('CASUALTIES_COUNT', models.IntegerField()),
                ('CATEGORY', models.CharField(max_length=50)),
            ],
        ),
    ]
